apiVersion: v1
kind: Pod
metadata:
  name: ${podName}
  labels:
    env: test
spec:
  containers:
  - name: ${podName}
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: ${vmInstanceName}
